package gui;

/*import java.text.NumberFormat;
import javax.swing.JFormattedTextField;
import javax.swing.text.NumberFormatter;*/
import javax.swing.JOptionPane;
import listasmusicales.Cancion;

public class JDNuevoCancion extends javax.swing.JDialog {

	private Cancion nuevaCancion;
	private boolean creado;

	public JDNuevoCancion(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		this.creado = false;
	}

	public JDNuevoCancion(java.awt.Frame parent, boolean modal, Cancion us) {
		this(parent, modal);

		this.jmTextoTitulo.setText("EDITAR CANCIÓN");
		this.jmBotonAñadir.setText("Confirmar");
		this.jTextTitulo.setText(us.getTitulo());
		this.jTextRuta.setText(us.getRuta());
		this.jTextDuracion.setText(us.getDuracion() + "");
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jmTextoTitulo = new javax.swing.JLabel();
      jmTitulo = new javax.swing.JLabel();
      jmDuracion = new javax.swing.JLabel();
      jTextTitulo = new javax.swing.JTextField();
      jmBotonAñadir = new javax.swing.JButton();
      jmBotonCancelar = new javax.swing.JButton();
      jTextDuracion = new javax.swing.JTextField();
      jTextRuta = new javax.swing.JTextField();
      jmRuta = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Crear Usuario");

      jmTextoTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jmTextoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jmTextoTitulo.setText("AÑADIR NUEVA CANCIÓN");

      jmTitulo.setText("Titulo:");

      jmDuracion.setText("Duración:");

      jmBotonAñadir.setText("Añadir");
      jmBotonAñadir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmBotonAñadirActionPerformed(evt);
         }
      });

      jmBotonCancelar.setText("Cancelar");
      jmBotonCancelar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmBotonCancelarActionPerformed(evt);
         }
      });

      jTextDuracion.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextDuracionActionPerformed(evt);
         }
      });

      jTextRuta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextRutaActionPerformed(evt);
         }
      });

      jmRuta.setText("Ruta:");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jmTextoTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(48, 48, 48)
                  .addComponent(jmBotonAñadir)
                  .addGap(37, 37, 37)
                  .addComponent(jmBotonCancelar))
               .addGroup(layout.createSequentialGroup()
                  .addGap(24, 24, 24)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jmRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextRuta))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jmTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jmDuracion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextDuracion)))))
            .addContainerGap(25, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jmTextoTitulo)
            .addGap(41, 41, 41)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jmTitulo)
               .addComponent(jTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jmRuta)
               .addComponent(jTextRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jmDuracion)
               .addComponent(jTextDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jmBotonAñadir)
               .addComponent(jmBotonCancelar))
            .addGap(25, 25, 25))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

	/**
	 * Comprobar si se ha creado alguna Cancion.
	 * 
	 * @return true si se ha creado alguna Cancion, false si no se ha creado ninguna Cancion.
	 */
	public boolean getCancionCreada() {
		return this.creado;
	}

	/**
	 * Devolver la Cancion creada.
	 * 
	 * @return la cancion creada, null si no se ha creado ninguna.
	 */
	public Cancion GetCancion() {
		return this.nuevaCancion;
	}

   private void jmBotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBotonCancelarActionPerformed
		this.setVisible(false);
   }//GEN-LAST:event_jmBotonCancelarActionPerformed

   private void jmBotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmBotonAñadirActionPerformed
		String titulo = jTextTitulo.getText();
		String ruta = jTextRuta.getText();
		String duracionText = jTextDuracion.getText();
		int duracion;
		String patron = "^[0-9]{1,9}$";
		if (duracionText.matches(patron) && !ruta.isBlank() && !titulo.isBlank()) {
			duracion = Integer.parseInt(jTextDuracion.getText());
			this.nuevaCancion = new Cancion(titulo, ruta, duracion);
			this.creado = true;
			this.setVisible(false);
		} else {
			JOptionPane.showMessageDialog(this, "Hay valores invalidos");
		}


   }//GEN-LAST:event_jmBotonAñadirActionPerformed

   private void jTextDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDuracionActionPerformed
		// TODO add your handling code here:
   }//GEN-LAST:event_jTextDuracionActionPerformed

   private void jTextRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRutaActionPerformed
		// TODO add your handling code here:
   }//GEN-LAST:event_jTextRutaActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JDNuevoCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JDNuevoCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JDNuevoCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JDNuevoCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				JDNuevoCancion dialog = new JDNuevoCancion(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField jTextDuracion;
   private javax.swing.JTextField jTextRuta;
   private javax.swing.JTextField jTextTitulo;
   private javax.swing.JButton jmBotonAñadir;
   private javax.swing.JButton jmBotonCancelar;
   private javax.swing.JLabel jmDuracion;
   private javax.swing.JLabel jmRuta;
   private javax.swing.JLabel jmTextoTitulo;
   private javax.swing.JLabel jmTitulo;
   // End of variables declaration//GEN-END:variables
}
